// <auto-generated />
namespace Nop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201801091534_VendorEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201801091534_VendorEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201801090735360_201801091534_VendorEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
